// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXebZ-sG3q4k8Q60ymxLBqy8VWtv5U6yY',
    appId: '1:1057077701872:web:715bdfe2a85da6cc352635',
    messagingSenderId: '1057077701872',
    projectId: 'neighbor-hub-33460',
    authDomain: 'neighbor-hub-33460.firebaseapp.com',
    storageBucket: 'neighbor-hub-33460.firebasestorage.app',
    measurementId: 'G-0SQGETLL8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6stV18j-ZbemaT5V5wR7tYwj1JbqyNd8',
    appId: '1:1057077701872:android:e23eaafa4b651530352635',
    messagingSenderId: '1057077701872',
    projectId: 'neighbor-hub-33460',
    storageBucket: 'neighbor-hub-33460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8tm94EAcCac5k1BQD22vDzf-x33y2dvM',
    appId: '1:1057077701872:ios:26337688c1af63ca352635',
    messagingSenderId: '1057077701872',
    projectId: 'neighbor-hub-33460',
    storageBucket: 'neighbor-hub-33460.firebasestorage.app',
    iosBundleId: 'com.example.neighborHubAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8tm94EAcCac5k1BQD22vDzf-x33y2dvM',
    appId: '1:1057077701872:ios:26337688c1af63ca352635',
    messagingSenderId: '1057077701872',
    projectId: 'neighbor-hub-33460',
    storageBucket: 'neighbor-hub-33460.firebasestorage.app',
    iosBundleId: 'com.example.neighborHubAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXebZ-sG3q4k8Q60ymxLBqy8VWtv5U6yY',
    appId: '1:1057077701872:web:6e5326ee49174ec0352635',
    messagingSenderId: '1057077701872',
    projectId: 'neighbor-hub-33460',
    authDomain: 'neighbor-hub-33460.firebaseapp.com',
    storageBucket: 'neighbor-hub-33460.firebasestorage.app',
    measurementId: 'G-5L3E20RJFG',
  );
}
